### ISSUE TITLE
Offline build

### ISSUE THREAD

**Issue by Bettelstab** [nimiq/keyguard#159]

**Comment by sisou** [comment]
The Nimiq lib is now included in the build as of #198.
Now only the Muli and Fira Mono font files are remaining online, but the Keyguard already works as an offline package now.

**Comment by Bettelstab** [comment]
Note: According to https://developers.google.com/fonts/faq#will_web_fonts_slow_down_my_page, it should be no legal problem to host the fonts ourselves.

**Comment by valentinvieriu** [comment]
I'm working on a train now, and keyguard demos are not working because of fonts.
Check https://google-webfonts-helper.herokuapp.com/

**Comment by valentinvieriu** [comment]
I'm working on a train now, and keyguard demos are not working because of fonts.
Check https://google-webfonts-helper.herokuapp.com/

**Comment by danimoh** [comment]
The fonts are packaged as of https://github.com/nimiq/keyguard/pull/311.
With this, I think the keyguard is now ready to run offline.
If you think something is missing, please reopen.
