### ISSUE TITLE
Vulnerability report

### ISSUE THREAD

**Issue by JafarAkhondali** [nimiq/keyguard#501]
We are a group of researchers from Leiden University, and we conduct research on vulnerabilities in open-source software. We have discovered and verified a high-severity vulnerability in your project(nimiq/keyguard). Explaining the vulnerability further in this issue could allow malicious users to access details, so we recommend [enabling private vulnerability reporting on GitHub](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) to discuss this matter confidentially.
        After you have enabled this feature, please add a comment to this issue so we can continue our discussion. If you have any questions, feel free to leave a reply here or send an email to: j.akhoundali [at] liacs.leidenuniv.nl

**Comment by sisou** [comment]
Hello @JafarAkhondali, thanks for reaching out!

For vulnerability reporting, we set up the email address security@nimiq.com. Please send any report there, it will be handled accordingly.

For more details, visit our bug bounty page: https://www.nimiq.com/bug-bounty/

**Comment by JafarAkhondali** [comment]
Hi, I got no response from this address, can you check your email, please?

**Comment by sisou** [comment]
Hello @JafarAkhondali we saw it, thanks! We don't think a path vulnerability in the dev server script is important to fix. One of these days we'll get to it.

**Comment by JafarAkhondali** [comment]
@sisou Ok, thanks. But please keep in mind that I or any other person who puts time into finding & reporting a vulnerability put some effort into validation and reporting. I didn't ask for something in return, but when you don't reply to a report, I go for follow-ups to ensure the response is received, so please in future consider replying to the emails.

**Comment by sisou** [comment]
Ref 91def328e55d4a9d3af9d42f67a0837aec258442.
